server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trailerlibrary
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Opsiyonel: SQL sorgular?n? konsolda g?stermek i?in
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
